### ISSUE TITLE
Report function as a JSON

### ISSUE THREAD

**Issue by aquintanas** [limdor/p2p-lending#20]
This issue discusses how it should be reported the information parsed and computed. In the last meeting (22 September 2021), it was agreed that the most feasible option seems to be a JSON. Accordingly, I propose the following structure:

```
date_of_report = {
    overall_statistics = {
        overall_investment = X,
        number_loan_parts = X,
    },
    country_statistics = {
        percentage_loans_in_single_country = X,
        percentage_loans_in_three_countries = X,
    },
    originator_statistics = {
         percentage_loans_in_single_originator = X,
         percentage_loans_in_five_originators = X,
    },
    country_investment_data = { 
        dataFile = Y,
    },
    originator_investment_data = {
        dataFile = Z,
    }
}
```

@limdor , we should discuss the following points:
- General structure
- Key names 
- How to store the data. Now I propose in a different file, but It could be included in the JSON.

Finally, I am not 100% sure that in the future, we won't have to change to an RDBM.

**Comment by limdor** [comment]
Some thoughts about this topic. Any proposal that we come up with, should come with an example that is a valid json.
https://jsonformatter.curiousconcept.com/
In addition we should specify also a json schema that we can validate against.
https://json-schema.org/learn/getting-started-step-by-step
Then any json file that is added or generated in the respository should have an automatic test that checks that the json is compliant with the schema.
This would be imho the minimum. The reason why this is the minimum is because with this way we will never have an invalid json and in case that we change the format we will see it clearly because the schema will also have to change.

About the parts of nice to have, we should consider some of the best practices to create json files. One option would be the google style guide: https://google.github.io/styleguide/jsoncstyleguide.xml

**Comment by aquintanas** [comment]
Done!

**Comment by limdor** [comment]
We should discuss if the json following the monthly report schema will be for a single marketplace or it will be aggregated accross them. If it is aggregated we will have to change dataFile to be a list of strings instead of a single string.
https://github.com/limdor/p2p-lending/blob/master/schemas/monthlyReport.json
