### ISSUE TITLE
Reconsider how we get the latest report date

### ISSUE THREAD

**Issue by limdor** [limdor/p2p-lending#45]
The application provides two modes, on to show past investements and another one to show only the latest.
The point here is how we calculate the latest date. If for one platform we have information of January and February and for the other we have January, February and March, the latest date will be different for both platforms.
This will mean that we will aggregate information for Platform A from February and Platform B from March. This is not necessary intuitive and can generate confusing.
We should consider in case we show only the latest information, to do it for the latest date that we have common for all platforms.

**Comment by aquintanas** [comment]
I think that users should pre-process the data. They must know what files are updating, at least at the current stage of our scripts. However, I agree that this must be revisited because there are different options, e.g. the last date can be the last snapshot that you have of your data independently of the month.
